// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Error(arg1:string,arg2:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function Notify(arg1:string,arg2:string):Promise<void>;

export function ReadFileData(arg1:string):Promise<any>;

export function SaveAsFile(arg1:any):Promise<string>;

export function SaveJsonToFile(arg1:string,arg2:any):Promise<string>;

export function SelectFile():Promise<main.FileResp>;

export function Warn(arg1:string,arg2:string):Promise<void>;
