// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Error(arg1, arg2) {
  return window['go']['main']['App']['Error'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Notify(arg1, arg2) {
  return window['go']['main']['App']['Notify'](arg1, arg2);
}

export function ReadFileData(arg1) {
  return window['go']['main']['App']['ReadFileData'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function Warn(arg1, arg2) {
  return window['go']['main']['App']['Warn'](arg1, arg2);
}
